### ISSUE TITLE
Cyrillic links don't work (they won't open) after 197282b commit

### ISSUE THREAD

**Issue by artkpv** [lervag/wiki.vim#395] opened 2024-12-24 10:54 UTC
# Description

This commit breaks my links :(, this means when I open a link it doesn't open a link, it opens an empty buffer, a new file while actually the file exists. I have links in Cyrillic. And I think `wiki#url#utils#url_encode_specific(a:url, '()')` replaces Cyrillic chars with URL entities, which is not the chars in the filesnames on my disk. 

When I revert this commit, 197282b, i.e. I checkout the commit just before it, my links work. 

# Minimal working example
Example:

```
- [Информатика](02 Информатика, Computer Science.md)
```
Steps:

1. Place your cursor at this link and press Enter

Result: New buffer opens '02 Информатика, Computer Science.md'. Message: "wiki: Opened a new page "02 Информатика, Computer Science.md"".
Expected result: It opens my file

My config:

```
  {
    'lervag/wiki.vim',
    lazy = false, -- we don't want to lazy load VimTeX
    config = function()
      vim.g.wiki_root = '/home/art/mydir/notes/'

      vim.g.wiki_select_method = {
        pages = require('wiki.telescope').pages,
        tags = require('wiki.telescope').tags,
        toc = require('wiki.telescope').toc,
        links = require('wiki.telescope').links,
      }
      vim.g.wiki_filetypes = { 'md' }

      vim.g.wiki_link_creation = {
        md = {
          link_type = 'md',
          url_extension = '.md',
        },
        _ = {
          link_type = 'md',
          url_extension = '.md',
        },
      }

      vim.g.wiki_month_names = {
        '01.Январь',
        '02.Февраль',
        '03.Март',
        '04.Апрель',
        '05.Май',
        '06.Июнь',
        '07.Июль',
        '08.Август',
        '09.Сентябрь',
        '10.Октябрь',
        '11.Ноябрь',
        '12.Декабрь',
      }
      vim.g.wiki_toc_title = 'Содержание'
      vim.g.wiki_journal = {
        -- index_use_journal_scheme = false,
        name = '2024',
        frequency = 'daily',
        date_format = {
          daily = '%Y-%m-%d',
        },
        root = '~/mydir/notes/2024',
      }

      vim.g.init_my_wiki_config = function()
        vim.opt.number = false
        vim.opt.relativenumber = false
        vim.opt.cursorline = false
        vim.opt.cursorcolumn = false
        vim.opt.foldcolumn = '0'
        vim.opt.list = false
        vim.opt.foldlevel = 1
        vim.diagnostic.enable(false)
        vim.cmd.colorscheme 'neobones'
        vim.o.laststatus = 1
        vim.o.ruler = false
        vim.cmd 'Copilot disable'
        vim.cmd 'LspStop'

        -- au! BufWritePost ~/mydir/notes/* !git add "%";git commit -m "Auto commit of %:t." "%"

        vim.api.nvim_create_autocmd('BufWritePost', {
          desc = 'Commit wiki changes',
          group = vim.api.nvim_create_augroup('wiki-commit-hook', { clear = true }),
          pattern = { '*.md' },
          callback = function()
            vim.cmd '!git add "%";git commit -m "Auto commit of %:t." "%"'
          end,
        })
      end
      vim.keymap.set('n', '<leader>wq', vim.g.init_my_wiki_config, { desc = 'Wiki [Q]uite mode on' })

      local function wiki_page_rename()
        local current_file = vim.fn.expand '%'
        local current_name = vim.fn.expand '%:t'
        local name = vim.fn.input('Enter new name (' .. current_name .. '): ')

        if name ~= '' then
          vim.fn.termopen { './ren.sh', current_file, name }
        end
      end

      vim.keymap.set('n', '<leader>wpr', wiki_page_rename, { desc = 'Rename wiki page' })
    end,
  },

```

**Comment by lervag** [comment] 2024-12-24 11:39
First, regarding your config:

* Please use `init = function()` (similar to VimTeX) for the wiki options; this is because there is a minor risk that setting options in `config` will be "too late" for wiki.vim to properly recognize them. This has a negligable init cost.
* "-- we don't want to lazy load VimTeX" <- I guess you mean wiki.vim here? :)
* You don't need to specify things unless you change them from defaults. E.g. you are not changing `g:wiki_filetypes`.

Now, one simple way to revert to the "old" behaviour for creating links would be to specify a trivial url transformer.

```lua
vim.g.wiki_link_creation = {
  md = {
    url_transform = function(x) return x end
  }
}
```

I think the following config (attached at the bottom) should be closer to what you want.

```lua
  {
    'lervag/wiki.vim',
    lazy = false,
    init = function()
      vim.g.wiki_root = '/home/art/mydir/notes/'

      vim.g.wiki_select_method = {
        pages = require('wiki.telescope').pages,
        tags = require('wiki.telescope').tags,
        toc = require('wiki.telescope').toc,
        links = require('wiki.telescope').links,
      }

      vim.g.wiki_link_creation = {
        md = {
          url_transform = function(x) return x end
        },
        _ = {
          link_type = 'md',
          url_extension = '.md',
        },
      }

      vim.g.wiki_month_names = {
        '01.Январь',
        '02.Февраль',
        '03.Март',
        '04.Апрель',
        '05.Май',
        '06.Июнь',
        '07.Июль',
        '08.Август',
        '09.Сентябрь',
        '10.Октябрь',
        '11.Ноябрь',
        '12.Декабрь',
      }
      vim.g.wiki_toc_title = 'Содержание'
      vim.g.wiki_journal = {
        -- index_use_journal_scheme = false,
        name = '2024',
        frequency = 'daily',
        date_format = {
          daily = '%Y-%m-%d',
        },
        root = '~/mydir/notes/2024',
      }
    end,
    config = function()
      vim.g.init_my_wiki_config = function()
        vim.opt.number = false
        vim.opt.relativenumber = false
        vim.opt.cursorline = false
        vim.opt.cursorcolumn = false
        vim.opt.foldcolumn = '0'
        vim.opt.list = false
        vim.opt.foldlevel = 1
        vim.diagnostic.enable(false)
        vim.cmd.colorscheme 'neobones'
        vim.o.laststatus = 1
        vim.o.ruler = false
        vim.cmd 'Copilot disable'
        vim.cmd 'LspStop'

        -- au! BufWritePost ~/mydir/notes/* !git add "%";git commit -m "Auto commit of %:t." "%"

        vim.api.nvim_create_autocmd('BufWritePost', {
          desc = 'Commit wiki changes',
          group = vim.api.nvim_create_augroup('wiki-commit-hook', { clear = true }),
          pattern = { '*.md' },
          callback = function()
            vim.cmd '!git add "%";git commit -m "Auto commit of %:t." "%"'
          end,
        })
      end
      vim.keymap.set('n', '<leader>wq', vim.g.init_my_wiki_config, { desc = 'Wiki [Q]uite mode on' })

      local function wiki_page_rename()
        local current_file = vim.fn.expand '%'
        local current_name = vim.fn.expand '%:t'
        local name = vim.fn.input('Enter new name (' .. current_name .. '): ')

        if name ~= '' then
          vim.fn.termopen { './ren.sh', current_file, name }
        end
      end

      vim.keymap.set('n', '<leader>wpr', wiki_page_rename, { desc = 'Rename wiki page' })
    end,
  },
```

**Comment by lervag** [comment] 2024-12-24 11:40
> This commit breaks my links :( I have links in Cyrillic. And I think `wiki#url#utils#url_encode_specific(a:url, '()')` replaces Cyrillic chars with URL entities, which is not the chars in the filesnames on my disk.

Can you explain a little bit better what you mean by "breaks my links"? That is, does it break the creation of links, following links, both, or something else?

**Comment by artkpv** [comment] 2024-12-24 16:24
@lervag 
> > This commit breaks my links :( I have links in Cyrillic. And I think `wiki#url#utils#url_encode_specific(a:url, '()')` replaces Cyrillic chars with URL entities, which is not the chars in the filesnames on my disk.
> 
> Can you explain a little bit better what you mean by "breaks my links"? That is, does it break the creation of links, following links, both, or something else?

I've updated it

**Comment by lervag** [comment] 2024-12-24 23:51
> When I revert this commit, [197282b](https://github.com/lervag/wiki.vim/commit/197282b271a4b829a3d3645d6fa5bf4180c413fd), i.e. I checkout the commit just before it, my links work.

I don't think this commit has anything to do with url encoding.

In your minimal example, can you outline it even further? That is, you only show a line in an unnamed file. Thus there are a lot of details not revealed.

If you create a temporary wiki at `~/tmpwiki` with three files, e.g.

```
~/tmpwiki
├─ index.md
└─ foo.md
└─ 02 Информатика, Computer Science.md
```

where `index.md` contains

```md
- [foo](foo.md)
- [Информатика](02 Информатика, Computer Science.md)
```

Can you confirm that

1. following the link to `foo.md` works as expected?
2. following the link to the other file does _not_ work with the same result as what you've outlined?

**Comment by lervag** [comment] 2024-12-24 23:54
Ok, I think I can reproduce now following the setup I outlined.

**Comment by lervag** [comment] 2024-12-24 23:58
Please update; I think this is fixed now.

**Closed by lervag** 2024-12-24 23:58 UTC

**Comment by artkpv** [comment] 2024-12-26 16:39
@lervag Yes, Cyrillic links now open. Thank you!

**Comment by lervag** [comment] 2024-12-26 23:13
My pleasure; thanks for opening the issue!
