### ISSUE TITLE
wiki_template is duplicated

### ISSUE THREAD

**Issue by Traap** [lervag/wiki.vim#328] opened 2023-12-11 19:24 UTC
A template is fired twice when creating a new page.  This occurs with both Vim and Neovim.  Here is how I product the problem:

THIS IS A REALLY SIMPLE TEST
* The text above is transformed to a wiki link.
  * Visually select text
  * Press return
  * link becomes: ```[THIS IS A REALLY SIMPLE TEST](this-is-a-really-simple.test.md)```
  * Confirm link is correct.
  * Press enter.
  * New Page is properly named but .template.md is fired twice.
  * See output

### this-is-a-really-simple-test.md
``` code
_This Is A Really Simple Test_
  Date: 2023-12-11 11:19
_This Is A Really Simple Test_
  Date: 2023-12-11 11:19
```

### Content of g:wiki_template
```code
let s:template = expand($WIKIHOME) . '/.template.md'

let g:wiki_templates = [
     \ { 'match_func': {x -> v:true}, 'source_filename': s:template},
     \]
```

### Content of PageNameTitleCase
``` code
function! PageNameTitleCase(ctx, text) abort
  let s:temp = substitute(a:text, '-', ' ', 'g')
  return substitute(s:temp, '\v<(.)(\w*)', '\u\1\L\2', 'g')
endfunction
```

### Content of .template.md
```code
_{{PageNameTitleCase {name}}}_
  Date: {date} {time}

```

**Comment by lervag** [comment] 2023-12-13 19:28
Thanks for a good issue report. However, I can't reproduce this. If I copy your settings here it seems to work exactly as expected.

Are you able to create a minimal config to test this? Something like this:

```vim
set nocompatible
set runtimepath^=~/.local/plugged/wiki.vim
filetype plugin indent on
syntax enable

let s:template = expand($WIKIHOME) . '/.template.md'

let g:wiki_root = '...'
" let g:wiki_OTHER SETTINGS
let g:wiki_templates = [
     \ { 'match_func': {x -> v:true}, 'source_filename': s:template},
     \]

function! PageNameTitleCase(ctx, text) abort
  let s:temp = substitute(a:text, '-', ' ', 'g')
  return substitute(s:temp, '\v<(.)(\w*)', '\u\1\L\2', 'g')
endfunction

nnoremap q :qall!<cr>
```

With this and possibly some adjustments, you should be able to do `nvim --clean -u minimal.vim` to start the testing and reproduce the problem.

**Comment by Traap** [comment] 2023-12-14 02:40
Hi Karl,
As always, thank you for your quick response and testing tip.  I pasted my entire minimal.vim file here just so you know how I am configuring wiki.vim.  Sadly, this test file does not reproduce the problem.  I am now certain the problem is somewhere else in my configuration.  I will review auto commands next.  I'll keep you posted with any findings should anyone encounter the same configuration issue.
Thanks.  Traap 
Gary Howard

```code
set nocompatible
set runtimepath^=~/.local/share/nvim/lazy/wiki.vim
filetype plugin indent on
syntax enable

" {{{ bundle-wiki.vim

if exists('g:loaded_bundle_wiki_vim')
  finish
endif
let g:loaded_bundle_wiki_vim=1

" -------------------------------------------------------------------------- }}}
" {{{ Settings based on Windoz Subsystem for Linux (WSL2) check.

if !empty(getenv('WSL_DISTRO_NAME'))
  let g:traap_pdf_viewer = 'SumatraPDF.exe'
  let g:traap_png_viewer = 'feh'
else
  let g:traap_pdf_viewer = 'okular'
  let g:traap_png_viewer = 'feh'
endif

" -------------------------------------------------------------------------- }}}
" {{{ Wiki.vim root

function! WikiRoot()
  let l:local = finddir('wiki', ';./')
  return !empty(l:local) ? l:local : expand($WIKIHOME)
endfunction

let g:wiki_root  = 'WikiRoot'

" -------------------------------------------------------------------------- }}}
" {{{ Wiki.vim General settings.

" General settings are listed alphabetically only because I find them faster.

let g:wiki_filetypes = ['md','csv','json','puml','sql','tex','texx','wiki','xml','yaml']

let g:wiki_link_extension = '.md'
let g:wiki_link_target_type = 'md'
let g:wiki_toc_depth = 2
let g:wiki_viewer = {
    \ 'pdf': g:traap_pdf_viewer,
    \   '_': 'xdg_open',
    \}

let g:wiki_write_on_nav = 1

" -------------------------------------------------------------------------- }}}
" {{{ Wiki.vim Export current page.

let g:wiki_export = {
    \ 'args' : '--metadata-file=$WIKIHOME/wiki.yaml',
    \ 'from_format' : 'markdown',
    \ 'ext' : 'pdf',
    \ 'link_ext_replace': v:false,
    \ 'view' : v:true,
    \ 'output': 'printed',
    \ 'viewer': g:traap_pdf_viewer,
    \}

" -------------------------------------------------------------------------- }}}
" {{{ Wiki.vim File Handler

let g:wiki_file_handler = 'WikiFileOpen'

function! WikiFileOpen(...) abort dict
  if self.path =~# 'pdf$'
    silent execute '!' g:traap_pdf_viewer fnameescape(self.path) '&'
    return 1
  endif

  if self.path =~# '\v(png|jpg)$'
    silent execute '!' g:traap_png_viewer fnameescape(self.path) '&'
    return 1
  endif

  return 0
endfunction

" -------------------------------------------------------------------------- }}}
" {{{ Wiki.vim Journal

let s:journal = 'journal'

let g:wiki_journal = {
    \  'name': s:journal,
    \  'frequency': 'daily',
    \  'date_format': {
    \    'daily' : '%Y-%m-%d',
    \    'weekly' : '%Y_w%V',
    \    'monthly' : '%Y_m%m',
    \  },
    \ 'root': '',
    \ 'index_use_journal_scheme': v:true,
    \}

" -------------------------------------------------------------------------- }}}
" {{{ Wiki.vim Link Creator

let g:wiki_link_creation = {
      \ 'md': {
      \   'link_type': 'md',
      \   'url_extension': '.md',
      \   'url_transform': { x ->
      \     substitute(tolower(x), '\s\+', '-', 'g') },
      \ },
      \ 'org': {
      \   'link_type': 'org',
      \   'url_extension': '.org',
      \   'url_transform': { x ->
      \     substitute(tolower(x), '\s\+', '-', 'g') },
      \ },
      \ 'adoc': {
      \   'link_type': 'adoc_xref_bracket',
      \   'url_extension': '',
      \   'url_transform': { x ->
      \     substitute(tolower(x), '\s\+', '-', 'g') },
      \ },
      \ '_': {
      \   'link_type': 'wiki',
      \   'url_extension': '',
      \   'url_transform': { x ->
      \     substitute(tolower(x), '\s\+', '-', 'g') },
      \ },
      \}


" -------------------------------------------------------------------------- }}}
" {{{ Wiki.vim Page Templates

let s:template = expand($WIKIHOME) . '/.template.md'

let g:wiki_templates = [
     \ { 'match_func': {x -> v:true}, 'source_filename': s:template},
     \]

" A-title-page-name becomes A Title Page Name.
"
" https://stackoverflow.com/questions/17440659/capitalize-first-letter-of-each-word-in-a-selection-using-vim#
"
function! PageNameTitleCase(ctx, text) abort
  let s:temp = substitute(a:text, '-', ' ', 'g')
  return substitute(s:temp, '\v<(.)(\w*)', '\u\1\L\2', 'g')
endfunction

" -------------------------------------------------------------------------- }}}

nnoremap q :qall!<cr>

```

**Comment by Traap** [comment] 2023-12-14 03:49
I corrected an auto command group.  I'll paste the code snippets below.

### autogroup function
```code
local function augroup(name)
  return vim.api.nvim_create_augroup("traap_" .. name, { clear = true })
end
```

### Invalid nvim_create_autocmd
```code
vim.api.nvim_create_autocmd({ "BufRead", "BufNewFile" }, {
  group = augroup("wiki"),
  command = "setlocal foldlevelstart=2 filetype=wiki | WikiEnable",
  pattern = { "*.md", "*.markdown", "*.wiki" },
})
```

### Valid nvim_create_autocmd
```code
vim.api.nvim_create_autocmd({ "BufRead", "BufNewFile" }, {
  group = augroup("wiki"),
  command = "setlocal foldlevelstart=2 filetype=wiki",
  pattern = { "*.md", "*.markdown", "*.wiki" },
})
```

Removing WikiEnable resolved my issue.

**Comment by lervag** [comment] 2023-12-15 22:53
First, a minor comment about formatting: You can have nice highlighting with github flavored markdown by using the correct language specifier in fenced code blocks. You wrote ```` ```code ````, which I've updated to ```` ```vim ````.

Now, I understand from your last comment that you figured things out and that I can safely close the issue; is that correct?

**Closed** 2023-12-15 22:54 UTC

**Comment by Traap** [comment] 2023-12-16 02:31
Thank you for the markdown code tip.

Yes, this item is closed.
