### ISSUE TITLE
Disabling default mappings might be broken

### ISSUE THREAD

**Issue by qadzek** [lervag/wiki.vim#360] opened 2024-05-16 16:34 UTC
First of all, thank you very much for this great plugin. I think I will use it instead of Vimwiki.

When using the following minimal setup:

```vim
let g:wiki_mappings_use_default = 'none'
Plug 'lervag/wiki.vim'
```

I expected no mappings would be set.

However, mappings like `<leader>wr` still seem to work.
Running `:verbose map <leader>w` shows a lot of mappings.

**Comment by lervag** [comment] 2024-05-16 18:14
> First of all, thank you very much for this great plugin. I think I will use it instead of Vimwiki.

♥️ 


> When using the following minimal setup:
> 
> ```viml
> let g:wiki_mappings_use_default = 'none'
> Plug 'lervag/wiki.vim'
> ```
> 
> I expected no mappings would be set.
> 
> However, mappings like `<leader>wr` still seem to work. Running `:verbose map <leader>w` shows a lot of mappings.

I can reproduce - will fix it asap!

**Comment by lervag** [comment] 2024-05-16 22:39
It turns out that it _does_ work, but only if you use the right option name: `g:wiki_mappings_use_defaults` with the plural s. I found one typo for this in the docs which I fixed now - it may have been the cause of the confusion.

**Closed by lervag** 2024-05-16 22:39 UTC
