### ISSUE TITLE
WikiGraphFindBacklinks - Windows, error running command (creating file)

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#156] opened 2021-05-24 13:54 UTC
Hello!

This is probably related to Windows paths again :(

```
Error detected while processing function wiki#graph@find_backlinks[2]..9[4]..<SNR>116_gather_nodes[43]..17:

E482: Can't create file C:\Users\Alex/.cache/wiki.vim/graphC:\Users\Alex\vimfiles\vimwiki.json
```

**Comment by lervag** [comment] 2021-05-26 21:18
Thanks. I'm looking at it now and I'll try to push a fix.

Please note: wiki.vim may have created a silly folder on your computer under `C:\Users\Alex` - please check.

**Comment by lervag** [comment] 2021-05-26 21:27
I think this should be fixed now, please test.

**Closed by lervag** 2021-05-26 21:27 UTC

**Comment by bybor** [comment] 2021-05-27 12:16
I'm sorry, I'm struggling with copying `:messages`

![2021-05-27 15_14_27-](https://user-images.githubusercontent.com/90693/119824330-75aa5580-befe-11eb-920e-49c3758d7b79.png)

**Comment by lervag** [comment] 2021-05-27 20:03
Ah, ok; this seems to be a new error. Can you help with further debugging here?

https://github.com/lervag/wiki.vim/blob/a16ed5d59f42afa5abde701c2d1b64b80a70bc7e/autoload/wiki/graph.vim#L15-L18

```vim
for l:link in l:results
  let l:link.filename = l:link.filename_from
  unsilent echom 1 string(keys(l:link))
  unsilent echom 2 l:link.filename
  unsilent echom 3 l:link.pos_start
  let l:link.text = readfile(l:link.filename, 0, l:link.pos_start[0])[-1]
endfor
```

I believe adding these `echom`s should help reveal what might be the problem here.

**Comment by bybor** [comment] 2021-05-28 07:06
OK, here is how it looks with those lines replaced

![2021-05-28 10_02_36-Window](https://user-images.githubusercontent.com/90693/119943956-5bbf5000-bf9c-11eb-89da-e05051924837.png)

**Comment by lervag** [comment] 2021-05-29 22:08
Thanks! And sorry, it seems there was a regression in some earlier refactoring that broke the graph backlink function. Please test again now.

**Comment by bybor** [comment] 2021-05-31 12:03
Thank you for the fix, works fine!

**Comment by lervag** [comment] 2021-05-31 12:22
Great, happy to hear it :)
