### ISSUE TITLE
How do I turn off a specific key mapping?

### ISSUE THREAD

**Issue by cryptogohan** [lervag/wiki.vim#159] opened 2021-06-04 10:51 UTC
# Description

I have <c-s> bound to saving. This plugin maps it to toggling a list item todo.

I found `let g:wiki_mappings_use_defaults = 'global'` but I'd still like all the other bindings!

**Comment by lervag** [comment] 2021-06-04 11:39
I assume you mean:

> I have bound `CTRL+s` to saving. ...

----

Thanks, I've pushed a fix. wiki.vim should now no longer override your own mappings.

> I found `let g:wiki_mappings_use_defaults = 'global'` but I'd still like all the other bindings!

Yes, sorry, there is currently not an easy way to disable a single mapping. If you still think this is necessary after the recent fix, then let me know.

**Closed by lervag** 2021-06-04 11:39 UTC

**Comment by kosciak** [comment] 2023-02-11 09:02
Just in case anyone stumble over this - there **is** an easy way to disable single mapping!

```vim
let g:wiki_mappings_local = {
      \ '<plug>(wiki-tag-list)': '<nop>',
      \ '<plug>(wiki-tag-search)': '<nop>',
      \ '<plug>(wiki-tag-reload)': '<nop>',
      \ '<plug>(wiki-tag-rename)': '<nop>',
      \}
```

BTW <plug>(wiki-tag-rename) is not listed on wiki-mappings-default section in help file (if you wander what else might use <leader>wl prefix)

**Comment by lervag** [comment] 2023-02-11 11:18
Thanks, @kosciak! I realized this feature was easy to implement so I just did. To disable a mapping, set it to an empty string.

Notice, your suggestion does not fully work as intended. You actually end up mapping the sequence `<nop>`, i.e. 5 keys, to the target rhs. I guess the probability of actually typing that sequence is tiny, so in practise, it probably does work. But with the recent update, we instead allow a proper way to disable a mapping.

**Comment by kosciak** [comment] 2023-02-11 12:28
Isn't `<nop>` special No-operation mapping? At least for RHS side of mapping. For LHS it might be better to use `<plug>` instead. 

Anyway, setting an empty string was first thing I tried so it'd definetely way to go

**Comment by lervag** [comment] 2023-02-11 12:32
> Isn't `<nop>` special No-operation mapping? At least for RHS side of mapping.

Yes, but in this case you are using it for the left-hand side! As specified in the docs, the values in this dictionary are the left-hand sides, whereas the _keys_ are the right-hand sides (the plug mappings).
