### ISSUE TITLE
new error message at startup "E715: Dictionary required"

### ISSUE THREAD

**Issue by alexandreroberts** [lervag/wiki.vim#321] opened 2023-08-29 19:58 UTC
I just updated all plugins and now get this error at startup. I haven't noticed any issues with functionality yet (but it would be nice not to see this every time I start up).

Before I try to produce a full bug report, I wanted to post the error message to check in case it's something obvious (to someone else) and easily fixable:
<img width="1430" alt="Screenshot 2023-08-29 at 9 51 48 PM" src="https://github.com/lervag/vimtex/assets/6886906/db693206-f1ae-4ee0-8bef-d619b9996dc5">

If not, I will try to make a proper bug report.

**Comment by lervag** [comment] 2023-08-29 20:04
See `:help wiki_select_method` - I relatively recently changed the option value type from a string to a dictionary. It was mentioned in the release notes.

**Comment by alexandreroberts** [comment] 2023-09-26 09:04
Thank you, that fixed it (sorry I never updated this thread).

But now I seem to have encountered a new breaking change. I just updated wiki.vim and now get this error message when trying to open a wiki file:
<img width="1435" alt="Screenshot 2023-09-26 at 11 03 04 AM" src="https://github.com/lervag/wiki.vim/assets/6886906/b0a609bb-88ac-4e68-b097-95dbca81bbb9">

I can try to make a bug report, but I suspect that again the fix might be obvious to you. I've tried looking at the recent commits but didn't see anything that stood out to me.

**Comment by alexandreroberts** [comment] 2023-09-26 09:06
There is another error message too, which says it can't open my wiki, which is a shame!

<img width="1434" alt="Screenshot 2023-09-26 at 11 05 27 AM" src="https://github.com/lervag/wiki.vim/assets/6886906/9a9f15ef-242e-422e-815b-c22501043c28">

**Comment by lervag** [comment] 2023-09-26 09:09
Notice that these errors come from fugitive and airline. I believe the error is caused by some update to one of these plugins. Can you disable them and check?

**Comment by alexandreroberts** [comment] 2023-09-26 09:15
You were right, that eliminated the error. But now something else strange is happening: it won't open my index.wiki file as it usually does, instead doing this:

<img width="655" alt="Screenshot 2023-09-26 at 11 13 32 AM" src="https://github.com/lervag/wiki.vim/assets/6886906/47684ebf-acd7-4570-a1cf-41f831833d09">

When I write `:e index.wiki`, it says "Permission Denied." Hm, maybe I will try restarting in case my permissions have simply been screwed up.

**Comment by lervag** [comment] 2023-09-26 09:33
Well, yes, this also seems like something not caused by wiki.vim, and it is very hard to make a good helpful comment. I'm curious, does the file `~/Documents/wikiNotepad/index.wiki` exist on your computer? Do you have access?

**Comment by alexandreroberts** [comment] 2023-09-26 09:34
Yes, that's the strange thing, I can open it (through the Finder on a Mac) with TextEdit. I will restart now and see what happens...

**Comment by lervag** [comment] 2023-09-26 09:55
Glad to hear it works! Can I close the issue?

**Comment by alexandreroberts** [comment] 2023-09-26 09:59
Yes, please close the issue. Thanks again!

**Closed** 2023-09-26 10:16 UTC
